---
- name: Deploy Docker Images
  hosts: all
  tasks:
    - name: Starting docker service
      service:
        name: docker
        state: started

    - name: Copy Docker Compose file from host machine to AWS EC2 Instance
      copy:
        src: ./docker-compose.yml
        dest: ./


